export const JD_SELECTORS = {
  homeSearchInput: [
    "#key",
    "input[name='keyword']",
    ".search-m input[type='text']",
    "input[id*='key']",
    "input[placeholder*='搜索']",
  ],
  homeSearchButton: [
    ".button",
    "button.button",
    ".form button",
    ".search-m button",
    ".search-btn",
    "button[aria-label*='搜索']",
  ],
  searchInput: [
    "#key",
    "input[name='keyword']",
    ".search-m input[type='text']",
    "input[id*='key']",
    "input[placeholder*='搜索']",
    ".search-form input[type='text']",
  ],
  searchButton: [
    ".button",
    "button.button",
    ".search-m button",
    ".search-btn",
    "button[aria-label*='搜索']",
    ".search-form button",
  ],
  resultCards: [
    "#J_goodsList .gl-item",
    ".gl-warp .gl-item",
    "li[data-sku]",
    "[data-sku]",
    ".goods-list-v2 li",
  ],
  resultContainers: [
    "#J_goodsList",
    ".gl-warp",
    ".goods-list-v2",
    "[class*='goods-list']",
    "[class*='result-list']",
  ],
  resultLoading: [
    ".loading-style1",
    ".loading-style2",
    ".j_loading",
    "[class*='loading']",
    "[class*='skeleton']",
  ],
  resultEmpty: [
    ".nf-content",
    ".no-result",
    "[class*='no-result']",
    "[class*='empty']",
  ],
  resultTitle: [
    ".p-name em",
    ".p-name a em",
    ".sku-name",
    "[class*='title'] a",
    "[class*='title'] em",
  ],
  resultLink: [
    ".p-name a",
    ".p-img a",
    "[class*='title'] a",
    "a[href*='item.jd.com/']",
    "a[href*='item.jd.hk/']",
    "a[target='_blank']",
  ],
  resultPrice: [
    ".p-price strong",
    ".p-price",
    ".price",
    "[class*='price'] strong",
    "[class*='price']",
  ],
  resultShop: [".p-shop a", ".curr-shop a", ".shopname", "[class*='shop'] a"],
  resultTagSpans: [".p-icons i", ".p-commit a", ".promo-words", "[class*='tag']", "[class*='icon']"],
  resultSummary: [".p-commit strong", ".p-promotions", ".p-ad", "[class*='summary']", "[class*='desc']"],
};
